version: '0.1'

services:
  cinematicketing.api:
    image: cinematicketing.api
    build:
      context: .
      dockerfile: CinemaTicketing.API/Dockerfile
    ports:
      - '8080:8080'
      - '8081:8081'
    environment:
      #- ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_ENVIRONMENT=Development
      #- ASPNETCORE_KESTREL__CERTIFICATES__DEFAULT__PATH=cert.pfx
      #- ASPNETCORE_HTTPS_PORTS=8081
      #depends_on:
      # db:
      #  condition: service_healthy
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    restart: always
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=yourStrong(!)Password
    healthcheck:
      test: /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P "yourStrong(!)Password" -Q "SELECT 1" -b -o /dev/null
      interval: 10s
      timeout: 3s
      retries: 10
      start_period: 10s
    ports:
      - '1433:1433'
